server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 1m
    max-connections: 8192
    accept-count: 100
    keep-alive-timeout: 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: pg-simulator
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml

datasource:
  mysql-jpa:
    main:
      jdbc-url: jdbc:mysql://localhost:3306/paymentgateway

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local, test

server:
  port: 8090

management:
  server:
    port: 8091

---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8090

management:
  server:
    port: 8091

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false
