### 대기열 진입
POST {{commerce-api}}/api/v1/queue/enter
X-Loopers-LoginId: testuser
X-Loopers-LoginPw: Test1234!

### 대기열 순번 조회 (Polling)
GET {{commerce-api}}/api/v1/queue/position
X-Loopers-LoginId: testuser
X-Loopers-LoginPw: Test1234!
